-- Esquema de la base de datos H2 en memoria para servicio-productos.
-- R2DBC no ejecuta automáticamente schema.sql; Spring Boot lo detecta
-- en el classpath y lo aplica al arrancar gracias a spring.sql.init.mode=always.

CREATE TABLE IF NOT EXISTS producto (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre      VARCHAR(255) NOT NULL,
    descripcion VARCHAR(1000),
    precio      DECIMAL(10, 2) NOT NULL,
    stock       INT NOT NULL DEFAULT 0
);

-- Datos de ejemplo para poder probar los endpoints sin insertar manualmente.
INSERT INTO producto (nombre, descripcion, precio, stock) VALUES
    ('Teclado mecánico', 'Teclado TKL con switches Cherry MX Red', 89.99, 50),
    ('Ratón gaming', 'Sensor óptico 16000 DPI, 6 botones programables', 49.99, 120),
    ('Monitor 27"', 'IPS 2K 165 Hz, 1 ms GTG, FreeSync Premium', 349.00, 15),
    ('Auriculares USB', 'Sonido 7.1 virtual, micrófono retráctil', 79.99, 30),
    ('Alfombrilla XL', 'Base de tela 90 × 40 cm, base antideslizante', 19.99, 200);
