FROM eclipse-temurin:25-jre
WORKDIR /app
COPY servicio-productos/build/libs/servicio-productos-1.0-SNAPSHOT.jar app.jar
EXPOSE 8083
ENTRYPOINT ["java", "-XX:MaxRAMPercentage=75.0", "-jar", "app.jar"]
