-- Esquema de la base de datos H2 en memoria para servicio-pedidos.
-- Spring Boot ejecuta este fichero al arrancar gracias a spring.sql.init.mode=always.

CREATE TABLE IF NOT EXISTS pedido (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    producto_id     BIGINT NOT NULL,
    cantidad        INT NOT NULL,
    estado          VARCHAR(50) NOT NULL DEFAULT 'PENDIENTE',
    fecha_creacion  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Datos de ejemplo para poder probar los endpoints sin crear pedidos manualmente.
INSERT INTO pedido (producto_id, cantidad, estado, fecha_creacion) VALUES
    (1, 2, 'CONFIRMADO', '2026-05-01 10:00:00'),
    (2, 1, 'PENDIENTE',  CURRENT_TIMESTAMP),
    (3, 3, 'CANCELADO',  '2026-05-10 14:30:00');
